#!/bin/bash
rostopic echo -b $1 -p /biotac_pub/bt_data[0]/electrode_data > $2_electrode1.txt
rostopic echo -b $1 -p /biotac_pub/bt_data[1]/electrode_data > $2_electrode2.txt
rostopic echo -b $1 -p /biotac_pub/bt_data[2]/electrode_data > $2_electrode3.txt
