#!/bin/bash
rostopic echo -b $1 -p /biotac_pub/bt_data[0]/pdc_data > $2_pdc1.txt
rostopic echo -b $1 -p /biotac_pub/bt_data[1]/pdc_data > $2_pdc2.txt
rostopic echo -b $1 -p /biotac_pub/bt_data[2]/pdc_data > $2_pdc3.txt
